export const Songs = [
  {
    id: 0,
    name: "Perfect",
    image: "/images/perfect.jpg",
    song: "/music_library/perfect.mp3",
    artist: "Ed Sheeran",
    released: "2017",
    genre: "Folk pop",
    lyricist: "	Ed Sheeran",
    prev: 11,
    next: 1,
    length: "4:23",
  },
  {
    id: 1,
    name: "Galway Girl",
    image: "/images/galwaygirl.jpg",
    song: "/music_library/galwaygirl.mp3",
    artist: "Ed Sheeran",
    released: "2017",
    genre: "Pop, Irish folk, Hip hop",
    lyricist:
      "Ed Sheeran, Amy Wadge, Damian McKee, Eamon Murray, Johnny McDaid, Liam Bradley",
    length: "2:52",
    prev: 0,
    next: 2,
  },
  {
    id: 2,
    name: "I Don't Care",
    image: "/images/idontcare.jpg",
    song: "/music_library/idontcare.mp3",
    artist: "Ed Sheeran & Justin Bieber",
    released: "2019",
    genre: "Electropop, Dancehall",
    lyricist:
      "Ed Sheeran, Justin Bieber, Max Martin, Shellback, Fred Gibson, Jason Boyd",
    prev: 1,
    next: 3,
    length: "3:37",
  },
  {
    id: 3,
    name: "Feel Me",
    image: "/images/feelme.jpg",
    song: "/music_library/feelme.mp3",
    artist: "Selena Gomez",
    released: "2016",
    genre: "Dance",
    lyricist:
      "Selena Gomez, Jacob Kasher, Ammar Malik, Ross Golan, Phil Shaouy, Lisa Scinta",
    prev: 2,
    next: 4,
    length: "3:45",
  },
  {
    id: 4,
    name: "We Don't Talk Anymore",
    image: "/images/wedonttalkanymore.jpg",
    song: "/music_library/wedonttalkanymore.mp3",
    artist: "Charlie Puth & Selena Gomez",
    released: "2016",
    genre: "Pop",
    lyricist: "Charlie Puth, Jacob Kasher Hindlin, Selena Gomez",
    prev: 3,
    next: 5,
    length: "3:50",
  },
  {
    id: 5,
    name: "Let Me Love You",
    image: "/images/letmeloveyou.jpg",
    song: "/music_library/letmeloveyou.mp3",
    artist: "Justin Bieber",
    released: "2016",
    genre: "EDMtropical house",
    lyricist:
      "William Grigahcine, Justin Bieber, Andrew Watt, Ali Tamposi, Brian Lee, Louis Bell",
    prev: 4,
    next: 6,
    length: "3:26",
  },
  {
    id: 6,
    name: "Despacito",
    image: "/images/despacito.jpg",
    song: "/music_library/despacito.mp3",
    artist: "Louis Fonsi & Daddy Yankee",
    released: "2017",
    genre: "Reggaeton, Latin pop",
    lyricist: "Luis Rodriguez, Erika Ender, Ramon Ayala",
    prev: 5,
    next: 7,
    length: "4:41",
  },
  {
    id: 7,
    name: "2002 - Acoustic",
    image: "/images/2002acoustic.jpg",
    song: "/music_library/2002acoustic.mp3",
    artist: "Anne Marie",
    released: "2018",
    genre: "Pop, R&B",
    lyricist:
      "Benjamin Levin, Julia Cavazos, Steve McCutcheon, Ed Sheeran, Anne-Marie",
    prev: 6,
    next: 8,
    length: "3:31",
  },
  {
    id: 8,
    name: "Dynamite",
    image: "/images/dynamite.jpg",
    song: "/music_library/dynamite.mp3",
    artist: "BTS",
    released: "2020",
    genre: "Disco-pop",
    lyricist: "David Stewart, Jessica Agombar",
    prev: 7,
    next: 9,
    length: "3:43",
  },
  {
    id: 9,
    name: "Love Me Like You Do",
    image: "/images/lovemelikeyoudo.jpg",
    song: "/music_library/lovemelikeyoudo.mp3",
    artist: "Ellie Goulding",
    released: "2014",
    genre: "Electropop",
    lyricist:
      "Max Martin, Savan Kotecha, Ilya Salmanzadeh, Ali Payami, Tove Nilsson",
    prev: 8,
    next: 10,
    length: "4:09",
  },
  {
    id: 10,
    name: "Starboy",
    image: "/images/starboy.jpg",
    song: "/music_library/starboy.mp3",
    artist: "The Weeknd",
    released: "2016",
    genre: "Alternative R&B, New wave, Pop, R&B",
    lyricist: "Doc McKinney, Henry Walter, Jason Quenneville",
    prev: 9,
    next: 11,
    length: "3:47",
  },
  {
    id: 11,
    name: "Closer",
    image: "/images/closer.jpg",
    song: "/music_library/closer.mp3",
    artist: "The Chainsmokers & Halsey",
    released: "2016",
    genre: "Future bass, Pop",
    lyricist:
      "Andrew Taggart, Ashley Frangipane, Shaun Frank, Frederic Kennett, Isaac King",
    prev: 10,
    next: 0,
    length: "4:21",
  },
];
