export const Songs = [
  {
    id: 1,
    name: "Galway Girl",
    image: "/images/galwaygirl.jpg",
    song: "/music_library/galwaygirl.mp3",
    artist: "Ed Sheeran",
  },
  {
    id: 2,
    name: "Perfect",
    image: "/images/perfect.jpg",
    song: "/music_library/perfect.mp3",
    artist: "Ed Sheeran",
  },
  {
    id: 3,
    name: "I Don't Care",
    image: "/images/idontcare.jpg",
    song: "/music_library/idontcare.mp3",
    artist: "Ed Sheeran & Justin Bieber",
  },
  {
    id: 4,
    name: "Feel Me",
    image: "/images/feelme.jpg",
    song: "/music_library/feelme.mp3",
    artist: "Selena Gomez",
  },
  {
    id: 5,
    name: "We Don't Talk Anymore",
    image: "/images/wedonttalkanymore.jpg",
    song: "/music_library/wedonttalkanymore.mp3",
    artist: "Charlie Puth & Selena Gomez",
  },
  {
    id: 6,
    name: "Let Me Love You",
    image: "/images/letmeloveyou.jpg",
    song: "/music_library/letmeloveyou.mp3",
    artist: "Justin Bieber",
  },
  {
    id: 7,
    name: "Despacito",
    image: "/images/despacito.jpg",
    song: "/music_library/despacito.mp3",
    artist: "Louis Fonsi & Daddy Yankee",
  },
  {
    id: 8,
    name: "2002 - Acoustic",
    image: "/images/2002acoustic.jpg",
    song: "/music_library/2002acoustic.mp3",
    artist: "Anne Marie",
  },
  {
    id: 9,
    name: "Dynamite",
    image: "/images/dynamite.jpg",
    song: "/music_library/dynamite.mp3",
    artist: "BTS",
  },
  {
    id: 10,
    name: "Love Me Like You Do",
    image: "/images/lovemelikeyoudo.jpg",
    song: "/music_library/lovemelikeyoudo.mp3",
    artist: "Ellie Goulding",
  },
  {
    id: 11,
    name: "Starboy",
    image: "/images/starboy.jpg",
    song: "/music_library/starboy.mp3",
    artist: "The Weeknd",
  },
  {
    id: 12,
    name: "Closer",
    image: "/images/closer.jpg",
    song: "/music_library/closer.mp3",
    artist: "The Chainsmokers",
  },
];
